name: YouTube Music

on:
  workflow_dispatch:
    inputs:
      apk_version:
        description: "APK Version"
        required: true
        default: "7.20.51"

env:
  REGISTRY: ghcr.io
  APK: youtube-music.apk
  REVANCED_OPTIONS: revanced-options.json
  REVANCED_CLI: revanced-cli-4.6.0-all.jar
  REVANCED_PATCHES: revanced-patches-4.15.0.jar
  REVANCED_INTEGRATIONS: revanced-integrations-1.14.2.apk

jobs:
  patch:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Get Last commit short SHA"
        id: "commit_short_sha"
        run: |
          echo "LAST_SHORT_COMMIT_SHA=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_OUTPUT

      - name: Downloading APK
        uses: Yakov5776/gh-apkmirror-dl@v1.2
        with:
          org: "google-inc"
          repo: "youtube-music"
          version: ${{ github.event.inputs.apk_version }}
          bundle: false
          filename: ${{ env.APK }}

      - name: Downloading ReVanced Cli
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "ReVanced/revanced-cli"
          version: "tags/v4.6.0"
          file: ${{ env.REVANCED_CLI }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Downloading ReVanced Patches
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "ReVanced/revanced-patches"
          version: "tags/v4.15.0"
          file: ${{ env.REVANCED_PATCHES }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Downloading ReVanced Integrations
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "ReVanced/revanced-integrations"
          version: "tags/v1.14.2"
          file: ${{ env.REVANCED_INTEGRATIONS }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Patching
        run: java -jar ${{ env.REVANCED_CLI }} patch -m ${{ env.REVANCED_INTEGRATIONS }} -b ${{ env.REVANCED_PATCHES }} --options ${{ env.REVANCED_OPTIONS }} -o patched-${{ env.APK }} ${{ env.APK }}

      - name: Downloading ReVanced GmsCore
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "ReVanced/GmsCore"
          version: "tags/v0.3.1.4.240913"
          file: "app.revanced.android.gms-240913008-signed.apk"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set current date as env variable
        run: echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          draft: true
          title: "Release ${{ env.date_now }}"
          files: |
            patched-${{ env.APK }}
            app.revanced.android.gms-240913008-signed.apk
